name: Home projects
description: Varius home project combined under single catalog
version: # Version of the Catalog to be used
category: Home
maintainer: github.5f16ec@tryninja.io
license: # The license
projectURL:  https://github.com/eneasz/rancher-catalog # A URL related to the catalog entry
