name: Plex Server
description: Plex Media Server
version: # Version of the Catalog to be used
category: Media
maintainer: eneasz
license: # The license
projectURL: # A URL related to the catalog entry
