plex:
  hostname: ${HOSTNAME}
  image: linuxserver/plex
  environment:
    - VERSION=latest
    - HOSTNAME=${HOSTNAME}
    - PUID=${PUID}
    - PGID=${PGID}
  ports:
    - ${PORT}:32400
  volumes:
    - ${PATHCONFIG}:/config
    - ${PATHMEDIA}:/data
  net: ${NET}