.catalog:
  name: Plex Server
  version: v0.1
  description: Plex Media Server
  questions:
    - variable: "HOSTNAME"
      type: "string"
      label: "HOSTNAME"
      default: "plex"
      description: Name to use for plex name on server list
    - variable: "PORT"
      type: "string"
      label: "PORT"
      description: Frontend Port of Plex
      default: 32400
    - variable: "PATHCONFIG"
      type: "string"
      label: "Config Path"
      description: persistang Path to your Plex Config (/var/lib/plexmediaserver, ...)
      default: '/home'
    - variable: "PATHMEDIA"
      type: "string"
      label: "Media Path"
      description: the Path to your library (/media, or a nfs mount /mnt, ...)
      default: '/data'
    - variable: "PUID"
      type: "string"
      label: "PUID"
      description: Plex GroupID (not required)
    - variable: "PGID"
      type: "string"
      label: "PGID"
      description: Plex PGID (not required)
    - variable: NET
      description: "select Network type"
      label: "Network"
      type: enum   
      options:
        - host
        - managed
        - none
      required: true
      default: "host"
Plex:
  scale: 1
