name: Sonarr Server
description: Sonarr Server
version: # Version of the Catalog to be used
category: Media
maintainer: github.5f16ec@tryninja.io
license: # The license
projectURL: # A URL related to the catalog entry
