name: UniFi Controller
description: UniFi Controller
version: # Version of the Catalog to be used
category: Network
maintainer: github.5f16ec@tryninja.io
license: # The license
projectURL: # A URL related to the catalog entry
