Sonarr:
  image: linuxserver/sonarr
  hostname: ${HOSTNAME}
  environment:
    - VERSION=latest
    - HOSTNAME=${HOSTNAME}
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
  ports:
    - ${PORT}:8989
  volumes:
    - ${PATHCONFIG}:/config
    - ${PATHTVSERIES}:${PATHTVSERIES}
    - /etc/localtime:/etc/localtime:ro
  net: ${NET}