.catalog:
  name: Sonarr Server
  version: v0.1
  description: Sonarr Server
  questions:
    - variable: "HOSTNAME"
      type: "string"
      label: "HOSTNAME"
      default: "sonarr"
      description: Name to use for radarr name on server list
    - variable: "PORT"
      type: "string"
      label: "PORT"
      description: Frontend Port of radarr
      default: 8989
    - variable: "PATHCONFIG"
      type: "string"
      label: "Config Path"
      description: Radarr Application Data (/var/lib/Sonarr, ...)
      default: '/var/lib/Sonarr'
    - variable: "PATHTVSERIES"
      type: "string"
      label: "TVSERIES Share"
      description: the Path to your TVSERIES library (/TVSERIES, or a nfs mount /mnt, ...)
      default: '/data/TV'
    - variable: "TZ"
      type: "string"
      label: "TZ"
      description: Time Zone
      default: "Europe/London"
    - variable: "PUID"
      type: "string"
      label: "PUID"
      description: plex GroupID (not required)
    - variable: "PGID"
      type: "string"
      label: "PGID"
      description: plex PGID (not required)
    - variable: NET
      description: "select Network type"
      label: "Network"
      type: enum   
      options:
        - host
        - managed
        - none
      required: true
      default: "host"
Sonarr:
  scale: 1
